<?xml version="1.0" encoding="utf-8"?><WebElementEntity>  
    <description/>  
    <name>i_编辑</name> 
    <tag/>  
    <elementGuidId>21fd958a-3329-11e8-95e1-acbc328db6eb</elementGuidId> 
    <selectorCollection>    
          <entry>     
              <key>BASIC</key>      
              <value/>      
          </entry>    
    </selectorCollection> 
    <selectorMethod>BASIC</selectorMethod>  
    <useRalativeImagePath>false</useRalativeImagePath>  
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>

   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;data-list&quot;]/div/div[2]/div[2]/div[1]/div[4]/i[1]</value>
   </webElementProperties>
</WebElementEntity>
