<?xml version="1.0" encoding="utf-8"?><WebElementEntity>	
   	<description/>	
   	<name>div_未选择导出项提示</name>	
   	<tag/>	
   	<elementGuidId>2894155a-36ef-11e8-bdda-985aebd8771a</elementGuidId>	
   	<selectorCollection>		
      		<entry>			
         			<key>BASIC</key>			
         			<value/>			
      		</entry>		
   	</selectorCollection>	
   	<selectorMethod>BASIC</selectorMethod>	
   	<useRalativeImagePath>false</useRalativeImagePath>	
   	<webElementProperties>    
            <isSelected>true</isSelected>    
            <matchCondition>equals</matchCondition>      
            <name>tag</name>     
            <type>Main</type>    
            <value>div</value>      
      </webElementProperties> 
      <webElementProperties>    
            <isSelected>true</isSelected>    
            <matchCondition>equals</matchCondition>      
            <name>xpath</name>      
            <type>Main</type>    
            <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini&quot;]/div[@class=&quot;alert alert-error alert-tip alert-top-center&quot;]</value>
      </webElementProperties> 
      <webElementProperties>
         <isSelected>true</isSelected>
         <matchCondition>equals</matchCondition>
         <name>text</name>
         <type>Main</type>
         <value>×请至少选择一条要导出的内容</value>
      </webElementProperties>
</WebElementEntity>