<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_板式样式</name>
   <tag></tag>
   <elementGuidId>78b98f36-2f58-11e8-aa28-985aebd8771a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/aside/section/ul/li/ul/li/a[count(. | //a[@href = '/technology/boardstyle' and (contains(text(), '板式样式') or contains(., '板式样式'))]) = count(//a[@href = '/technology/boardstyle' and (contains(text(), '板式样式') or contains(., '板式样式'))])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/aside/section/ul/li/ul/li/a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/technology/boardstyle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>板式样式</value>
   </webElementProperties>
</WebElementEntity>
