<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_公司邮箱</name>
   <tag></tag>
   <elementGuidId>7fc39d63-b200-417b-bed5-043b7ddf20fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value/> 
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
     <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;data-list&quot;]/div/div[3]/input</value>
   </webElementProperties>
</WebElementEntity>