<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_品牌名称</name>
   <tag></tag>
   <elementGuidId>1c44a51c-ec4f-4227-a607-b8e2ee576bf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value/> 
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;data-list&quot;]/div/div[1]/input</value>
   </webElementProperties>
</WebElementEntity>
