<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_公司地址</name>
   <tag></tag>
   <elementGuidId>0deeb3a8-af02-45f6-8a98-d4e3dcd970e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
        <value/>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;data-list&quot;]/div/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
