<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>原料测试</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-03-21T12:44:38</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <testSuiteGuid>f0abc216-edd9-460f-ae9b-2ce156c31a14</testSuiteGuid>
   <testCaseLink>
      <guid>38ce8d56-18ab-4855-8771-5397364b6737</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/yuanliaoguanli/yuanliaoliebiao-xinzeng</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34b56e27-cf46-40fa-9917-d6984ab07e27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fd5e05f-3e05-47d5-bfd4-26ecabaa751d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9106abf0-df83-4760-9f38-fc228e6b4100</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae3630d3-15cf-45c4-8524-664b2475d4d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>953768f3-21b4-443f-ba15-3c629171ea93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d9b3e71-a7f4-45ae-a347-a5d550f2d2fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8cd35e6-3d9e-491e-a98f-7e3c40ad70b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d777bf7-3915-4b10-8110-7c0f6f7b24fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d68de3a9-8c8b-4114-a697-66b7049ec645</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>092f181d-b938-4407-9f9f-a846362e7bc1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e311654a-2b56-4238-9b3f-ffa58727e492</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7b9d6f7-d662-4d16-8b5c-b89c62836a90</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14dd0245-320e-4953-b901-7f2871156d86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55ff18f8-7cec-46a5-881f-840359425936</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da381240-39ba-4ae7-a5de-4603f66a9dcb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e3936f7-0f3d-465f-a88c-8499fdceb4ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b73ef6f-121a-452d-95ac-790c7d7f79bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d29af1f-01da-4636-85c6-4b7e59a14a06</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ef9df491-11db-41d5-8ef4-c401e912ab51</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/yuanliaoguanli/yuanliaoliebiao-bianji</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fd5e05f-3e05-47d5-bfd4-26ecabaa751d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9106abf0-df83-4760-9f38-fc228e6b4100</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae3630d3-15cf-45c4-8524-664b2475d4d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>953768f3-21b4-443f-ba15-3c629171ea93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d9b3e71-a7f4-45ae-a347-a5d550f2d2fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8cd35e6-3d9e-491e-a98f-7e3c40ad70b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d777bf7-3915-4b10-8110-7c0f6f7b24fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92002dc5-93b6-4ddc-a7c1-d2cb68c5a8b7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1ebd8b89-2292-4b65-a5f6-da278f88160c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/yuanliaoguanli/yuanliaoliebiao-gongneng</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2efe6e9b-4e86-44d9-9187-e6867adde5e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2754e55b-616e-4c76-ab4c-fee457581b12</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f04e87ae-0f57-4757-a465-49a9b6d431e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/yuanliaoguanli/yuanliaoliebiao-shanchu</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>338f4f60-e6ce-4f07-96ed-cc88454307df</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
