<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>成品测试</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-03-22T09:47:53</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>3a978278-7ad7-4ff4-b7d1-6840c6721e9e</testSuiteGuid>
   <testCaseLink>
      <guid>2ae9838b-ed53-45ca-b733-f5b523b78794</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/jinxiaocun/chengpinguanli/chengpinliebiao-xinzeng</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8812f1f-736a-4cfe-b8f0-d19472a43b40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da3b56fd-ea6e-44b2-b987-2b04102d6702</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3de16dee-28c7-11e8-b02b-50af736c2359</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da3b56fd-ea6e-44b2-b987-2b04102d6702</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99324a1e-28c8-11e8-9746-50af736c2359</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6f65064-28c8-11e8-97e8-50af736c2359</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f98d2c8a-28c8-11e8-b1c6-50af736c2359</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23b35818-28c9-11e8-953c-50af736c2359</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02972c9f-a4b2-43d7-9e91-2bf6feea4b15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ba7587d-c71d-480f-a3c2-ce692430581f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10f177d5-b97b-471a-8a13-d07f0d928266</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>399f7587-ef66-4d48-bbb3-f4a98268ab72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/jinxiaocun/chengpinguanli/chengpinliebiao-bianji</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba9fdeb0-28e0-11e8-bb71-50af736c2359</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3612bfa-28e0-11e8-80ee-50af736c2359</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5059da0a-28e1-11e8-ae8e-50af736c2359</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5525ad90-28e1-11e8-bb7b-50af736c2359</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58c1cad4-28e1-11e8-ad42-50af736c2359</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>615e1b90-28e1-11e8-86d1-50af736c2359</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>669d5f26-28e1-11e8-a41e-50af736c2359</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6aec7210-28e1-11e8-8960-50af736c2359</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfc4b26f-2291-421d-9904-e314edbb6d20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b220fc34-ec9e-4950-8d35-24fee8920888</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7721e869-6f49-4776-b951-5413bfb31a04</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/jinxiaocun/chengpinguanli/chengpinguanli-liebiaocaozuo</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>abda0291-76cc-43a4-ad6c-901964766261</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/jinxiaocun/chengpinguanli/chengpinguanli-shanchu</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8a3af0f-bbab-4e6b-b797-53bc8ee7fc27</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
