<?xml version="1.0" encoding="utf-8"?><WebElementEntity>  
    <description/>  
    <name>span_消息管理</name>  
    <tag/>  
    <elementGuidId>06a63712-30cc-11e8-aad8-acbc328db6eb</elementGuidId> 
    <selectorCollection>    
          <entry>     
              <key>BASIC</key>      
              <value/>      
          </entry>    
    </selectorCollection> 
    <selectorMethod>BASIC</selectorMethod>  
    <useRalativeImagePath>false</useRalativeImagePath>  
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>tag</name>    
          <type>Main</type>   
          <value>span</value>    
    </webElementProperties> 
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>xpath</name>    
          <type>Main</type>   
          <value>html[1]/body[@class=&quot;skin-blue sidebar-mini&quot;]/aside[@class=&quot;main-sidebar&quot;]/section[@class=&quot;sidebar&quot;]/ul[@class=&quot;sidebar-menu&quot;]/li[@class=&quot;treeviewclass  #{item.hide ? item.hide.join(' ' : '')}&quot;]/a[1]/span[1]</value>    
    </webElementProperties> 
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>text</name>    
          <type>Main</type>   
          <value>消息管理</value>    
    </webElementProperties> 
</WebElementEntity>