<?xml version="1.0" encoding="utf-8"?><WebElementEntity>	
   	<description/>	
   	<name>span_产品管理</name>	
   	<tag/>	
   	<elementGuidId>25de41d2-36e0-11e8-9f86-005056c00008</elementGuidId>	
   	<selectorCollection>		
      		<entry>			
         			<key>BASIC</key>			
         			<value/>			
      		</entry>		
   	</selectorCollection>	
   	<selectorMethod>BASIC</selectorMethod>	
   	<useRalativeImagePath>false</useRalativeImagePath>	
   	<webElementProperties>		
      		<isSelected>true</isSelected>		
      		<matchCondition>equals</matchCondition>		
      		<name>tag</name>		
      		<type>Main</type>		
      		<value>span</value>		
   	</webElementProperties>	
   	<webElementProperties>		
      		<isSelected>true</isSelected>		
      		<matchCondition>equals</matchCondition>		
      		<name>xpath</name>		
      		<type>Main</type>		
      		<value>/html[1]/body[@class=&quot;skin-blue sidebar-mini&quot;]/aside[@class=&quot;main-sidebar&quot;]/section[@class=&quot;sidebar&quot;]/ul[@class=&quot;sidebar-menu&quot;]/li/a[1]/span[1]</value>		
   	</webElementProperties>	
      <webElementProperties>
         <isSelected>true</isSelected>
         <matchCondition>contains</matchCondition>
         <name>text</name>
         <type>Main</type>
         <value>产品管理</value>
      </webElementProperties>
</WebElementEntity>