<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_默认sku2</name>
   <tag></tag>
   <elementGuidId>277abf00-c8f6-4b60-b8b2-351180b08131</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;form1&quot;]/div/div[12]/div/div[2]/table/tbody/tr[2]/td[2]/input[count(. | //input[@type = 'radio']) = count(//input[@type = 'radio'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;form1&quot;]/div/div[12]/div/div[2]/table/tbody/tr[2]/td[2]/input</value>
   </webElementProperties>
</WebElementEntity>
