<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_文章时间</name>
   <tag></tag>
   <elementGuidId>18216361-028c-4fdd-afb5-259f5ac264df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
          <value/> 
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;modelbanner&quot;]/div/div/div[2]/div[5]/input</value>
   </webElementProperties>
</WebElementEntity>