<?xml version="1.0" encoding="utf-8"?><WebElementEntity>	
   	<description/>	
   	<name>a_生产任务单列表</name>	
   	<tag/>	
   	<elementGuidId>6262f450-37bb-11e8-b938-985aebd8771a</elementGuidId>	
   	<selectorCollection>		
      		<entry>			
         			<key>BASIC</key>			
         			<value/>			
      		</entry>		
   	</selectorCollection>	
   	<selectorMethod>BASIC</selectorMethod>	
   	<useRalativeImagePath>false</useRalativeImagePath>	
   	<webElementProperties>    
            <isSelected>true</isSelected>    
            <matchCondition>equals</matchCondition>      
            <name>tag</name>     
            <type>Main</type>    
            <value>a</value>     
      </webElementProperties> 
      <webElementProperties>     
            <isSelected>true</isSelected>    
            <matchCondition>equals</matchCondition>      
            <name>xpath</name>      
            <type>Main</type>    
            <value>/html/body/aside/section/ul/li[31]/ul/li[2]/a</value>      
      </webElementProperties> 
      <webElementProperties>
         <isSelected>true</isSelected>
         <matchCondition>equals</matchCondition>
         <name>href</name>
         <type>Main</type>
         <value>/productbatch/orderlist</value>
      </webElementProperties>
      <webElementProperties>
         <isSelected>true</isSelected>
         <matchCondition>contains</matchCondition>
         <name>text</name>
         <type>Main</type>
         <value>生产任务单列表</value>
      </webElementProperties>
</WebElementEntity>