<?xml version="1.0" encoding="utf-8"?><WebElementEntity>	
   	<description/>	
   	<name>input_只看启用</name>	
   	<tag/>	
   	<elementGuidId>d6791ff6-30cf-11e8-b289-985aebd8771a</elementGuidId>	
   	<selectorCollection>		
      		<entry>			
         			<key>BASIC</key>			
         			<value/>			
      		</entry>		
   	</selectorCollection>	
   	<selectorMethod>BASIC</selectorMethod>	
   	<useRalativeImagePath>false</useRalativeImagePath>	
   	<webElementProperties>		
      		<isSelected>true</isSelected>		
      		<matchCondition>equals</matchCondition>		
      		<name>tag</name>		
      		<type>Main</type>		
      		<value>input</value>		
   	</webElementProperties>	
   	<webElementProperties>		
      		<isSelected>true</isSelected>		
      		<matchCondition>equals</matchCondition>		
      		<name>xpath</name>		
      		<type>Main</type>		
      		<value>//*[@id=&quot;data-list&quot;]/div[1]/div/div[1]/label/input</value>		
   	</webElementProperties>	
      <webElementProperties>
         <isSelected>true</isSelected>
         <matchCondition>equals</matchCondition>
         <name>type</name>
         <type>Main</type>
         <value>checkbox</value>
      </webElementProperties>
</WebElementEntity>