<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_files_作品图</name>
   <tag></tag>
   <elementGuidId>43b0be18-9665-4e7f-9ca4-cacc3fe2d155</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;uploadWorks&quot;]/input[count(. | //input[@name = 'files' and @onchange = 'Core.uploadChange(this)' and @type = 'file']) = count(//input[@name = 'files' and @onchange = 'Core.uploadChange(this)' and @type = 'file'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;uploadWorks&quot;]/input</value>
   </webElementProperties>
</WebElementEntity>
