<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_产品组成_添加</name>
   <tag></tag>
   <elementGuidId>51f8f345-47d0-4d40-986e-25663d87eba3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/section[2]/div/div[2]/div[2]/div[4]/div/div/button[1][count(. | //button[@class = 'btn btn-flat bg-purple left' and (text() = '添加' or . = '添加')]) = count(//button[@class = 'btn btn-flat bg-purple left' and (text() = '添加' or . = '添加')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-flat bg-purple left</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>添加</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/section[2]/div/div[2]/div[2]/div[4]/div/div/button[1]</value>
   </webElementProperties>
</WebElementEntity>
