<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_编辑</name>
   <tag></tag>
   <elementGuidId>884ff8e0-091e-4330-b29c-a1edf9cbfc14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;data-list&quot;]/div/div[1]/div[3]/div/div[2]/div/table/tbody/tr[1]/td[8]/a[1]/i[count(. | //i[@class = 'fa-self-icon fa-self-edit']) = count(//i[@class = 'fa-self-icon fa-self-edit'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-self-icon fa-self-edit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;data-list&quot;]/div/div[1]/div[3]/div/div[2]/div/table/tbody/tr[1]/td[8]/a[1]/i</value>
   </webElementProperties>
</WebElementEntity>
