<?xml version="1.0" encoding="utf-8"?><WebElementEntity>  
    <description/>  
    <name>button_三证分开</name>  
    <tag/>  
    <elementGuidId>57be5cf8-3331-11e8-adac-408d5ca59395</elementGuidId> 
    <selectorCollection>    
          <entry>     
              <key>BASIC</key>      
              <value/>      
          </entry>    
    </selectorCollection> 
    <selectorMethod>BASIC</selectorMethod>  
    <useRalativeImagePath>false</useRalativeImagePath>  
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>tag</name>    
          <type>Main</type>   
          <value>button</value>    
    </webElementProperties> 
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>xpath</name>    
          <type>Main</type>   
          <value>//*[@id=&quot;form1&quot;]/div[2]/div[2]/div[1]/div/button[2]</value>    
    </webElementProperties> 
</WebElementEntity>
