<?xml version="1.0" encoding="utf-8"?><WebElementEntity>  
    <description/>  
    <name>input_logo</name> 
    <tag/>  
    <elementGuidId>99959ffe-33e2-11e8-a6aa-408d5ca59395</elementGuidId> 
    <selectorCollection>    
          <entry>     
              <key>BASIC</key>      
              <value/>      
          </entry>    
    </selectorCollection> 
    <selectorMethod>BASIC</selectorMethod>  
    <useRalativeImagePath>false</useRalativeImagePath>  
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>tag</name>    
          <type>Main</type>   
          <value>input</value>    
    </webElementProperties> 
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>xpath</name>    
          <type>Main</type>   
          <value>//*[@id=&quot;form1&quot;]/div[2]/div[1]/div/div[2]/input</value>    
    </webElementProperties>
    <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>files</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
   </webElementProperties>
</WebElementEntity>
