<?xml version="1.0" encoding="utf-8"?><WebElementEntity>  
    <description/>  
    <name>input_税务登记</name> 
    <tag/>  
    <elementGuidId>2422b0ae-3331-11e8-bcfa-408d5ca59395</elementGuidId> 
    <selectorCollection>    
          <entry>     
              <key>BASIC</key>      
              <value/>      
          </entry>    
    </selectorCollection> 
    <selectorMethod>BASIC</selectorMethod>  
    <useRalativeImagePath>false</useRalativeImagePath>  
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>tag</name>    
          <type>Main</type>   
          <value>input</value>    
    </webElementProperties> 
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>xpath</name>    
          <type>Main</type>   
          <value>//*[@id=&quot;form1&quot;]/div[2]/div[2]/div[3]/div[3]/div/div[2]/input</value>    
    </webElementProperties> 
</WebElementEntity>
