<?xml version="1.0" encoding="utf-8"?><WebElementEntity>  
    <description/>  
    <name>select_服务区域省</name> 
    <tag/>  
    <elementGuidId>8e4e88ec-3333-11e8-bd1a-408d5ca59395</elementGuidId> 
    <selectorCollection>    
          <entry>     
              <key>BASIC</key>      
              <value/>      
          </entry>    
    </selectorCollection> 
    <selectorMethod>BASIC</selectorMethod>  
    <useRalativeImagePath>false</useRalativeImagePath>  
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>tag</name>    
          <type>Main</type>   
          <value>select</value>    
    </webElementProperties> 
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>xpath</name>    
          <type>Main</type>   
          <value>//*[@id=&quot;form1&quot;]/div[2]/div[8]/div/div/div[1]/select</value>    
    </webElementProperties> 
</WebElementEntity>
