<?xml version="1.0" encoding="utf-8"?><WebElementEntity>	
   	<description/>	
   	<name>input_搜索框</name>	
   	<tag/>	
   	<elementGuidId>e4e19a00-3322-11e8-8690-985aebd8771a</elementGuidId>	
   	<selectorCollection>		
      		<entry>			
         			<key>BASIC</key>			
         			<value/>			
      		</entry>		
   	</selectorCollection>	
   	<selectorMethod>BASIC</selectorMethod>	
   	<useRalativeImagePath>false</useRalativeImagePath>	
   	<webElementProperties>		
      		<isSelected>true</isSelected>		
      		<matchCondition>equals</matchCondition>		
      		<name>tag</name>		
      		<type>Main</type>		
      		<value>input</value>		
   	</webElementProperties>	
   	<webElementProperties>		
      		<isSelected>true</isSelected>		
      		<matchCondition>equals</matchCondition>		
      		<name>xpath</name>		
      		<type>Main</type>		
      		<value>//*[@id=&quot;data-list&quot;]/div[1]/div/div[2]/input</value>		
   	</webElementProperties>	
      <webElementProperties>
         <isSelected>true</isSelected>
         <matchCondition>equals</matchCondition>
         <name>placeholder</name>
         <type>Main</type>
         <value>连接方案名称</value>
      </webElementProperties>
      <webElementProperties>
         <isSelected>true</isSelected>
         <matchCondition>equals</matchCondition>
         <name>type</name>
         <type>Main</type>
         <value>text</value>
      </webElementProperties>
      <webElementProperties>
         <isSelected>false</isSelected>
         <matchCondition>equals</matchCondition>
         <name>class</name>
         <type>Main</type>
         <value>form-control col-xs-4</value>
      </webElementProperties>
</WebElementEntity>