<?xml version="1.0" encoding="utf-8"?><WebElementEntity>  
    <description/>  
    <name>i_删除</name> 
    <tag/>  
    <elementGuidId>8deb0222-33b8-11e8-82fb-acbc328db6eb</elementGuidId> 
    <selectorCollection>    
          <entry>     
              <key>BASIC</key>
              <value/>      
          </entry>    
    </selectorCollection> 
    <selectorMethod>BASIC</selectorMethod>  
    <useRalativeImagePath>false</useRalativeImagePath>  
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>tag</name>    
          <type>Main</type>   
          <value>i</value>    
    </webElementProperties> 
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>xpath</name>    
          <type>Main</type>   
          <value>//*[@id=&quot;data-list&quot;]/div[2]/table/tbody/tr[1]/td[6]/i[2]</value>    
    </webElementProperties>
        <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttoncz store-hide bg-h</value>
   </webElementProperties>
</WebElementEntity>