<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_材质预览图上传按钮容器</name>
   <tag></tag>
   <elementGuidId>8ce44dc4-bdff-456e-a52a-c4d01bad6781</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;form1&quot;]/div[2]/div[2]/div[2]/div/div/ul/li[3]/div</value>
   </webElementProperties>
</WebElementEntity>
