<?xml version="1.0" encoding="utf-8"?><WebElementEntity>  
    <description/>  
    <name>select_省</name> 
    <tag/>  
    <elementGuidId>06c08102-36e5-11e8-9be1-acbc328db6eb</elementGuidId> 
    <selectorCollection>    
          <entry>     
              <key>BASIC</key>      
              <value/>      
          </entry>    
    </selectorCollection> 
    <selectorMethod>BASIC</selectorMethod>  
    <useRalativeImagePath>false</useRalativeImagePath>  
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>tag</name>    
          <type>Main</type>   
          <value>select</value>    
    </webElementProperties> 
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>xpath</name>    
          <type>Main</type>   
          <value>//*[@id=&quot;data-list&quot;]/div[1]/div/div[4]/div/div/div[1]/select</value>    
    </webElementProperties> 
</WebElementEntity>