<?xml version="1.0" encoding="utf-8"?><WebElementEntity>  
    <description/>  
    <name>input_新增区域名称</name> 
    <tag/>  
    <elementGuidId>c7b7f27e-32f7-11e8-958b-408d5ca59395</elementGuidId> 
    <selectorCollection>    
          <entry>     
              <key>BASIC</key>      
              <value/>      
          </entry>    
    </selectorCollection> 
    <selectorMethod>BASIC</selectorMethod>  
    <useRalativeImagePath>false</useRalativeImagePath>  
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>tag</name>    
          <type>Main</type>   
          <value>input</value>    
    </webElementProperties> 
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>xpath</name>    
          <type>Main</type>   
          <value>//*[@id=&quot;form1&quot;]/div/div/div/div/div[1]/input</value>    
    </webElementProperties> 
</WebElementEntity>
