<?xml version="1.0" encoding="utf-8"?><WebElementEntity>  
    <description/>  
    <name>select_新增市</name> 
    <tag/>  
    <elementGuidId>f8f89886-32f7-11e8-b9f6-408d5ca59395</elementGuidId> 
    <selectorCollection>    
          <entry>     
              <key>BASIC</key>      
              <value/>      
          </entry>    
    </selectorCollection> 
    <selectorMethod>BASIC</selectorMethod>  
    <useRalativeImagePath>false</useRalativeImagePath>  
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>tag</name>    
          <type>Main</type>   
          <value>select</value>    
    </webElementProperties> 
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>xpath</name>    
          <type>Main</type>   
          <value>//*[@id=&quot;form1&quot;]/div/div/div/div/div[2]/div/div[1]/div/div[2]/select</value>    
    </webElementProperties> 
</WebElementEntity>
