<?xml version="1.0" encoding="utf-8"?><WebElementEntity>  
    <description/>  
    <name>textarea_新增文字说明</name>  
    <tag/>  
    <elementGuidId>6fe13f1e-32f8-11e8-8599-408d5ca59395</elementGuidId> 
    <selectorCollection>    
          <entry>     
              <key>BASIC</key>      
              <value/>      
          </entry>    
    </selectorCollection> 
    <selectorMethod>BASIC</selectorMethod>  
    <useRalativeImagePath>false</useRalativeImagePath>  
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>tag</name>    
          <type>Main</type>   
          <value>textarea</value>    
    </webElementProperties> 
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>xpath</name>    
          <type>Main</type>   
          <value>//*[@id=&quot;form1&quot;]/div/div/div/div/div[3]/textarea</value>    
    </webElementProperties> 
</WebElementEntity>
