<?xml version="1.0" encoding="utf-8"?><WebElementEntity>	
   	<description/>	
   	<name>input_供货方地址</name>	
   	<tag/>	
   	<elementGuidId>b97e2e6e-3651-11e8-8f6b-985aebd8771a</elementGuidId>	
   	<selectorCollection>		
      		<entry>			
         			<key>BASIC</key>			
         			<value/>			
      		</entry>		
   	</selectorCollection>	
   	<selectorMethod>BASIC</selectorMethod>	
   	<useRalativeImagePath>false</useRalativeImagePath>	
   	<webElementProperties>    
            <isSelected>true</isSelected>    
            <matchCondition>equals</matchCondition>
            <name>tag</name>     
            <type>Main</type>    
            <value>input</value>    
      </webElementProperties> 
      <webElementProperties>     
            <isSelected>true</isSelected>    
            <matchCondition>equals</matchCondition>      
            <name>xpath</name>      
            <type>Main</type>    
            <value>//*[@id=&quot;form1&quot;]/div[9]/input</value>      
      </webElementProperties> 
      <webElementProperties>
         <isSelected>true</isSelected>
         <matchCondition>equals</matchCondition>
         <name>type</name>
         <type>Main</type>
         <value>text</value>
      </webElementProperties>
      <webElementProperties>
         <isSelected>false</isSelected>
         <matchCondition>equals</matchCondition>
         <name>class</name>
         <type>Main</type>
         <value>form-control</value>
      </webElementProperties>
</WebElementEntity>