<?xml version="1.0" encoding="utf-8"?><WebElementEntity>  
    <description/>  
    <name>button_搜索</name>  
    <tag/>  
    <elementGuidId>44b5eb1a-32f2-11e8-8c0a-408d5ca59395</elementGuidId> 
    <selectorCollection>    
          <entry>     
              <key>BASIC</key>      
              <value/>      
          </entry>    
    </selectorCollection> 
    <selectorMethod>BASIC</selectorMethod>  
    <useRalativeImagePath>false</useRalativeImagePath>  
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>tag</name>    
          <type>Main</type>   
          <value>button</value>    
    </webElementProperties> 
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>xpath</name>    
          <type>Main</type>   
          <value>/html/body/div[2]/section[2]/div/div[1]/div/div/button</value>    
    </webElementProperties> 
</WebElementEntity>
