<?xml version="1.0" encoding="utf-8"?><WebElementEntity>	
   	<description/>	
   	<name>a_pad首页设置</name>	
   	<tag/>	
   	<elementGuidId>0101d8ac-36eb-11e8-8fd7-b8e8562fba4a</elementGuidId>	
   	<selectorCollection>		
      		<entry>			
         			<key>BASIC</key>			
         			<value/>			
      		</entry>		
   	</selectorCollection>	
   	<selectorMethod>BASIC</selectorMethod>	
   	<useRalativeImagePath>false</useRalativeImagePath>	
      <webElementProperties>
         <isSelected>true</isSelected>
         <matchCondition>equals</matchCondition>
         <name>tag</name>
         <type>Main</type>
         <value>a</value>
      </webElementProperties>
      <webElementProperties>
         <isSelected>false</isSelected>
         <matchCondition>equals</matchCondition>
         <name>xpath</name>
         <type>Main</type>
         <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini&quot;]/aside[@class=&quot;main-sidebar&quot;]/section[@class=&quot;sidebar&quot;]/ul[@class=&quot;sidebar-menu&quot;]/li[@class=&quot;treeviewclass  #{item.hide ? item.hide.join(' ' : '')} active&quot;]/ul[@class=&quot;treeview-menu menu-open&quot;]/li[@class=&quot;&quot;]/a[1]</value>
      </webElementProperties>
      <webElementProperties>
         <isSelected>true</isSelected>
         <matchCondition>equals</matchCondition>
         <name>href</name>
         <type>Main</type>
         <value>/appmanage/list</value>
      </webElementProperties>
      <webElementProperties>
         <isSelected>true</isSelected>
         <matchCondition>contains</matchCondition>
         <name>text</name>
         <type>Main</type>
         <value>pad首页设置</value>
      </webElementProperties>
</WebElementEntity>