<?xml version="1.0" encoding="utf-8"?><WebElementEntity>  
    <description/>  
    <name>a_云展厅配置</name>  
    <tag/>  
    <elementGuidId>9b37d878-3161-11e8-8fd4-acbc328db6eb</elementGuidId> 
    <selectorCollection>    
          <entry>     
              <key>BASIC</key>      
              <value/>      
          </entry>    
    </selectorCollection> 
    <selectorMethod>BASIC</selectorMethod>  
    <useRalativeImagePath>false</useRalativeImagePath>  
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>tag</name>    
          <type>Main</type>   
          <value>a</value>    
    </webElementProperties> 
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>xpath</name>    
          <type>Main</type>   
          <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini&quot;]/aside[@class=&quot;main-sidebar&quot;]/section[@class=&quot;sidebar&quot;]/ul[@class=&quot;sidebar-menu&quot;]/li/ul[@class=&quot;treeview-menu menu-open&quot;]/li/a[1]</value>    
    </webElementProperties> 
    <webElementProperties>
          <isSelected>true</isSelected>
          <matchCondition>equals</matchCondition>
          <name>href</name>
          <type>Main</type>
          <value>/hall/select</value>
    </webElementProperties>
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>text</name>    
          <type>Main</type>   
          <value>云展厅配置</value>    
    </webElementProperties> 
</WebElementEntity>