<?xml version="1.0" encoding="utf-8"?><WebElementEntity>	
   	<description/>	
   	<name>button_保存资质文件</name>	
   	<tag/>	
   	<elementGuidId>bc5f4b94-3709-11e8-b124-b8e8562fba4a</elementGuidId>	
   	<selectorCollection>		
      		<entry>			
         			<key>BASIC</key>			
         			<value/>			
      		</entry>		
   	</selectorCollection>	
   	<selectorMethod>BASIC</selectorMethod>	
   	<useRalativeImagePath>false</useRalativeImagePath>	
      <webElementProperties>     
            <isSelected>true</isSelected>    
            <matchCondition>equals</matchCondition>      
            <name>tag</name>     
            <type>Main</type>    
            <value>button</value>      
      </webElementProperties> 
      <webElementProperties>     
            <isSelected>true</isSelected>    
            <matchCondition>equals</matchCondition>      
            <name>xpath</name>      
            <type>Main</type>    
            <value>//*[@id="addQualify"]/div/div/div[3]/button[1]</value>    
      </webElementProperties> 
</WebElementEntity>