<?xml version="1.0" encoding="utf-8"?><WebElementEntity>	
   	<description/>	
   	<name>span_禁用</name>	
   	<tag/>	
   	<elementGuidId>f3cbda02-36f0-11e8-9f47-b8e8562fba4a</elementGuidId>	
   	<selectorCollection>		
      		<entry>			
         			<key>BASIC</key>			
         			<value/>			
      		</entry>		
   	</selectorCollection>	
   	<selectorMethod>BASIC</selectorMethod>	
   	<useRalativeImagePath>false</useRalativeImagePath>	
       <webElementProperties>    
             <isSelected>true</isSelected>   
             <matchCondition>equals</matchCondition>   
             <name>tag</name>    
             <type>Main</type>   
             <value>span</value>    
       </webElementProperties> 
       <webElementProperties>    
             <isSelected>true</isSelected>   
             <matchCondition>equals</matchCondition>   
             <name>xpath</name>    
             <type>Main</type>   
             <value>/html/body/div[2]/section[2]/div/div[1]/div/div[2]/div/span[2]</value>    
       </webElementProperties> 
</WebElementEntity>