<?xml version="1.0" encoding="utf-8"?><WebElementEntity>	
   	<description/>	
   	<name>li_点击二级分类</name>	
   	<tag/>	
   	<elementGuidId>662d9278-3b99-11e8-a494-005056c00008</elementGuidId>	
   	<selectorCollection>		
      		<entry>			
         			<key>BASIC</key>			
         			<value/>			
      		</entry>		
   	</selectorCollection>	
   	<selectorMethod>BASIC</selectorMethod>	
   	<useRalativeImagePath>false</useRalativeImagePath>	
   	<webElementProperties>		
      		<isSelected>true</isSelected>		
      		<matchCondition>equals</matchCondition>		
      		<name>tag</name>		
      		<type>Main</type>		
      		<value>li</value>		
   	</webElementProperties>	
   	<webElementProperties>		
      		<isSelected>true</isSelected>		
      		<matchCondition>equals</matchCondition>		
      		<name>xpath</name>		
      		<type>Main</type>		
      		<value>//*[@id=&quot;sortable&quot;]/li[1]</value>		
   	</webElementProperties>	
</WebElementEntity>