<?xml version="1.0" encoding="utf-8"?><WebElementEntity>	
   	<description/>	
   	<name>span_启用</name>	
   	<tag/>	
   	<elementGuidId>dac355a2-3b99-11e8-bd95-005056c00008</elementGuidId>	
   	<selectorCollection>		
      		<entry>			
         			<key>BASIC</key>			
         			<value/>			
      		</entry>		
   	</selectorCollection>	
   	<selectorMethod>BASIC</selectorMethod>	
   	<useRalativeImagePath>false</useRalativeImagePath>	
   	<webElementProperties>		
      		<isSelected>true</isSelected>		
      		<matchCondition>equals</matchCondition>		
      		<name>tag</name>		
      		<type>Main</type>		
      		<value>span</value>		
   	</webElementProperties>	
   	<webElementProperties>		
      		<isSelected>true</isSelected>		
      		<matchCondition>equals</matchCondition>		
      		<name>xpath</name>		
      		<type>Main</type>		
      		<value>/html/body/div[2]/section[2]/div/div/div/div/div[3]/div/ul/li[1]/span</value>
   	</webElementProperties>	
</WebElementEntity>