<?xml version="1.0" encoding="utf-8"?><WebElementEntity>  
    <description/>  
    <name>input_跳转链接</name> 
    <tag/>  
    <elementGuidId>5b4bef5c-3336-11e8-b85b-acbc328db6eb</elementGuidId> 
    <selectorCollection>    
          <entry>     
              <key>BASIC</key>      
              <value/>      
          </entry>    
    </selectorCollection> 
    <selectorMethod>BASIC</selectorMethod>  
    <useRalativeImagePath>false</useRalativeImagePath>  
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;modelbanner&quot;]/div/div/div[2]/div[7]/input</value>
   </webElementProperties>
</WebElementEntity>