<?xml version="1.0" encoding="utf-8"?><WebElementEntity>  
    <description/>  
    <name>textarea_文字描述</name> 
    <tag/>  
    <elementGuidId>f4f99d8a-3335-11e8-96be-acbc328db6eb</elementGuidId> 
    <selectorCollection>    
          <entry>     
              <key>BASIC</key>      
              <value/>      
          </entry>    
    </selectorCollection> 
    <selectorMethod>BASIC</selectorMethod>  
    <useRalativeImagePath>false</useRalativeImagePath>  
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;modelbanner&quot;]/div/div/div[2]/div[5]/textarea</value>
   </webElementProperties>
</WebElementEntity>