<?xml version="1.0" encoding="utf-8"?><WebElementEntity>  
    <description/>  
    <name>i_删除</name> 
    <tag/>  
    <elementGuidId>06c5866c-33f3-11e8-96d7-408d5ca59395</elementGuidId> 
    <selectorCollection>    
          <entry>     
              <key>BASIC</key>      
              <value/>      
          </entry>    
    </selectorCollection> 
    <selectorMethod>BASIC</selectorMethod>  
    <useRalativeImagePath>false</useRalativeImagePath>  
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>tag</name>    
          <type>Main</type>   
          <value>i</value>    
    </webElementProperties> 
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>xpath</name>    
          <type>Main</type>   
          <value>//*[@id=&quot;data-list&quot;]/div[2]/table/tbody/tr/td[7]/a[2]/i</value>    
    </webElementProperties> 
</WebElementEntity>
