<?xml version="1.0" encoding="utf-8"?><WebElementEntity>	
   	<description/>	
   	<name>a_新增</name>	
   	<tag/>	
   	<elementGuidId>d6bb0358-37b9-11e8-b4a9-985aebd8771a</elementGuidId>	
   	<selectorCollection>		
      		<entry>			
         			<key>BASIC</key>			
         			<value/>			
      		</entry>		
   	</selectorCollection>	
   	<selectorMethod>BASIC</selectorMethod>	
   	<useRalativeImagePath>false</useRalativeImagePath>	
   	<webElementProperties>		
      		<isSelected>true</isSelected>		
      		<matchCondition>equals</matchCondition>		
      		<name>tag</name>		
      		<type>Main</type>		
      		<value>a</value>		
   	</webElementProperties>	
   	<webElementProperties>		
      		<isSelected>true</isSelected>		
      		<matchCondition>equals</matchCondition>		
      		<name>xpath</name>		
      		<type>Main</type>		
      		<value>//*[@id=&quot;data-list&quot;]/div[1]/div/a</value>		
   	</webElementProperties>	
      <webElementProperties>
         <isSelected>false</isSelected>
         <matchCondition>equals</matchCondition>
         <name>class</name>
         <type>Main</type>
         <value>btn btn-flat bg-olive left</value>
      </webElementProperties>
</WebElementEntity>