<?xml version="1.0" encoding="utf-8"?><WebElementEntity>  
    <description/>  
    <name>textarea_文字说明</name>  
    <tag/>  
    <elementGuidId>c0d0a7be-33f1-11e8-8910-408d5ca59395</elementGuidId> 
    <selectorCollection>    
          <entry>     
              <key>BASIC</key>      
              <value/>      
          </entry>    
    </selectorCollection> 
    <selectorMethod>BASIC</selectorMethod>  
    <useRalativeImagePath>false</useRalativeImagePath>  
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>tag</name>    
          <type>Main</type>   
          <value>textarea</value>    
    </webElementProperties> 
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>xpath</name>    
          <type>Main</type>   
          <value>/html/body/div[2]/section[2]/div/div/div/div/div[2]/textarea</value>    
    </webElementProperties> 
</WebElementEntity>
