<?xml version="1.0" encoding="utf-8"?><WebElementEntity>  
    <description/>  
    <name>a_审核</name> 
    <tag/>  
    <elementGuidId>6667b14a-332b-11e8-bef6-408d5ca59395</elementGuidId> 
    <selectorCollection>    
          <entry>     
              <key>BASIC</key>      
              <value/>      
          </entry>    
    </selectorCollection> 
    <selectorMethod>BASIC</selectorMethod>  
    <useRalativeImagePath>false</useRalativeImagePath>  
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>tag</name>    
          <type>Main</type>   
          <value>a</value>    
    </webElementProperties> 
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>xpath</name>    
          <type>Main</type>   
          <value>//*[@id=&quot;data-list&quot;]/table/tbody/tr[1]/td[10]/a[5]</value>    
    </webElementProperties> 
</WebElementEntity>
