<?xml version="1.0" encoding="utf-8"?><WebElementEntity>  
    <description/>  
    <name>span_禁用</name>  
    <tag/>  
    <elementGuidId>004c2782-3327-11e8-ae8e-408d5ca59395</elementGuidId> 
    <selectorCollection>    
          <entry>     
              <key>BASIC</key>      
              <value/>      
          </entry>    
    </selectorCollection> 
    <selectorMethod>BASIC</selectorMethod>  
    <useRalativeImagePath>false</useRalativeImagePath>  
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>tag</name>    
          <type>Main</type>   
          <value>span</value>    
    </webElementProperties> 
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>xpath</name>    
          <type>Main</type>   
          <value>//*[@id=&quot;data-list&quot;]/table/tbody/tr/td[9]/span[1]</value>    
    </webElementProperties> 
</WebElementEntity>
