<?xml version="1.0" encoding="utf-8"?><WebElementEntity>  
    <description/>  
    <name>textarea_禁用原因</name>  
    <tag/>  
    <elementGuidId>b6e2f6b8-332b-11e8-a6ad-408d5ca59395</elementGuidId> 
    <selectorCollection>    
          <entry>     
              <key>BASIC</key>      
              <value/>      
          </entry>    
    </selectorCollection> 
    <selectorMethod>BASIC</selectorMethod>  
    <useRalativeImagePath>false</useRalativeImagePath>  
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>tag</name>    
          <type>Main</type>   
          <value>textarea</value>    
    </webElementProperties> 
    <webElementProperties>    
          <isSelected>true</isSelected>   
          <matchCondition>equals</matchCondition>   
          <name>xpath</name>    
          <type>Main</type>   
          <value>//*[@id=&quot;checkopinion&quot;]</value>    
    </webElementProperties> 
</WebElementEntity>
